Need the name of the layer
If only the layer object is used, an error occurs.

TypeError: Layer names must be strings, not RLayer.

System used was Python 3.5.2 on Ubuntu Xenial 16.04 amd64